$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  sequencing_units_path:
    type: string
    description: path to sample-sheet TSV file

